export const ADD_ARTICLE = "ADD_ARTICLE";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

// character actions
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_ALIGNMENT = "UPDATE_ALIGNMENT";
export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const UPDATE_LEVEL = "UPDATE_LEVEL";
export const UPDATE_DIETY = "UPDATE_DIETY";
export const UPDATE_HOMELAND = "UPDATE_HOMELAND";
export const UPDATE_RACE = "UPDATE_RACE";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_GENDER = "UPDATE_GENDER";
export const UPDATE_AGE = "UPDATE_AGE";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";
export const UPDATE_HAIR = "UPDATE_HAIR";
export const UPDATE_EYES = "UPDATE_EYES";
// health point actions
export const UPDATE_MAX_HP = "UPDATE_MAX_HP";
export const UPDATE_CURRENT_HP = "UPDATE_CURRENT_HP";
export const UPDATE_NONLETHAL = "UPDATE_NONLETHAL";
export const UPDATE_INITIATIVE_MOD = "UPDATE_INITIATIVE_MOD";
export const UPDATE_DR = "UPDATE_DR";
// stat point actions
export const INCREMENT_STR = "INCREMENT_STR";
export const INCREMENT_DEX = "INCREMENT_DEX";
export const INCREMENT_CON = "INCREMENT_CON";
export const INCREMENT_INT = "INCREMENT_INT";
export const INCREMENT_WIS = "INCREMENT_WIS";
export const INCREMENT_CHA = "INCREMENT_CHA";
export const DECREMENT_STR = "DECREMENT_STR";
export const DECREMENT_DEX = "DECREMENT_DEX";
export const DECREMENT_CON = "DECREMENT_CON";
export const DECREMENT_INT = "DECREMENT_INT";
export const DECREMENT_WIS = "DECREMENT_WIS";
export const DECREMENT_CHA = "DECREMENT_CHA";
export const INCREMENT_STR_TEMP = "INCREMENT_STR_TEMP";
export const INCREMENT_DEX_TEMP = "INCREMENT_DEX_TEMP";
export const INCREMENT_CON_TEMP = "INCREMENT_CON_TEMP";
export const INCREMENT_INT_TEMP = "INCREMENT_INT_TEMP";
export const INCREMENT_WIS_TEMP = "INCREMENT_WIS_TEMP";
export const INCREMENT_CHA_TEMP = "INCREMENT_CHA_TEMP";
export const DECREMENT_STR_TEMP = "DECREMENT_STR_TEMP";
export const DECREMENT_DEX_TEMP = "DECREMENT_DEX_TEMP";
export const DECREMENT_CON_TEMP = "DECREMENT_CON_TEMP";
export const DECREMENT_INT_TEMP = "DECREMENT_INT_TEMP";
export const DECREMENT_WIS_TEMP = "DECREMENT_WIS_TEMP";
export const DECREMENT_CHA_TEMP = "DECREMENT_CHA_TEMP";

// skill actions
export const UPDATE_SKILL_RANK = "UPDATE_SKILL_RANK";
export const UPDATE_SKILL_DESCRIPTION = "UPDATE_SKILL_DESCRIPTION";
export const UPDATE_SKILL_MISC_MOD = "UPDATE_SKILL_MISC_MOD";
export const UPDATE_SKILL_IS_CLASS = "UPDATE_SKILL_IS_CLASS";

// movement actions
export const UPDATE_BASE_SPEED = "UPDATE_BASE_SPEED";
export const UPDATE_BASE_SPEED_ARMORED = "UPDATE_BASE_SPEED_ARMORED";
export const UPDATE_FLY_SPEED = "UPDATE_FLY_SPEED";
export const UPDATE_FLY_MANEUVERABILITY = "UPDATE_FLY_MANEUVERABILITY";
export const UPDATE_SWIM_SPEED = "UPDATE_SWIM_SPEED";
export const UPDATE_CLIMB_SPEED = "UPDATE_CLIMB_SPEED";
export const UPDATE_BURROW_SPEED = "UPDATE_BURROW_SPEED";

//armor class actions
export const UPDATE_ARMOR_BONUS = "UPDATE_ARMOR_BONUS";
export const UPDATE_SHIELD_BONUS = "UPDATE_SHIELD_BONUS";
export const UPDATE_SIZE_MODIFIER = "UPDATE_SIZE_MODIFIER";
export const UPDATE_NATURAL_ARMOR = "UPDATE_NATURAL_ARMOR";
export const UPDATE_DEFLECTION_MODIFIER = "UPDATE_DEFLECTION_MODIFIER";
export const UPDATE_ARMOR_MISC_MODIFIER = "UPDATE_ARMOR_MISC_MODIFIER";
export const UPDATE_TOUCH_ARMOR_CLASS = "UPDATE_TOUCH_ARMOR_CLASS";
export const UPDATE_FLAT_FOOTED_ARMOR_CLASS = "UPDATE_FLAT_FOOTED_ARMOR_CLASS";
export const UPDATE_AC_MODIFIERS_FIELD = "UPDATE_AC_MODIFIERS_FIELD";

//saves actions
export const UPDATE_BASE_SAVE = "UPDATE_BASE_SAVE";
export const UPDATE_MAGIC_SAVE_MODIFIER = "UPDATE_MAGIC_SAVE_MODIFIER";
export const UPDATE_MISC_SAVE_MODIFIER = "UPDATE_MISC_SAVE_MODIFIER";
export const UPDATE_TEMP_SAVE_MODIFIER = "UPDATE_TEMP_SAVE_MODIFIER";

//base attack bonus actions
export const UPDATE_BASE_ATTACK_BONUS = "UPDATE_BASE_ATTACK_BONUS";
export const UPDATE_SPELL_RESISTANCE = "UPDATE_SPELL_RESISTANCE";

//combat manuever bonus/defense
export const UPDATE_CMB_SIZE_MODIFIER = "UPDATE_CMB_SIZE_MODIFIER";
export const UPDATE_CMB_MODIFIERS_FIELD = "UPDATE_CMB_MODIFIERS_FIELD";
export const UPDATE_CMD_SIZE_MODIFIER = "UPDATE_CMD_SIZE_MODIFIER";

//weapon actions
export const UPDATE_WEAPON_NAME = "UPDATE_WEAPON_NAME";
export const UPDATE_WEAPON_ATTACK_BONUS = "UPDATE_WEAPON_ATTACK_BONUS";
export const UPDATE_WEAPON_CRITICAL = "UPDATE_WEAPON_CRITICAL";
export const UPDATE_WEAPON_TYPE = "UPDATE_WEAPON_TYPE";
export const UPDATE_WEAPON_RANGE = "UPDATE_WEAPON_RANGE";
export const UPDATE_WEAPON_AMMUNITION = "UPDATE_WEAPON_AMMUNITION";
export const UPDATE_WEAPON_DAMAGE = "UPDATE_WEAPON_DAMAGE";


