export const ADD_ARTICLE = "ADD_ARTICLE";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

//character actions
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_ALIGNMENT = "UPDATE_ALIGNMENT";
export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const UPDATE_LEVEL = "UPDATE_LEVEL";
export const UPDATE_DIETY = "UPDATE_DIETY";
export const UPDATE_HOMELAND = "UPDATE_HOMELAND";
export const UPDATE_RACE = "UPDATE_RACE";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_GENDER = "UPDATE_GENDER";
export const UPDATE_AGE = "UPDATE_AGE";
export const UPDATE_HEIGHT = "UPDATE_HEIGHT";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";
export const UPDATE_HAIR = "UPDATE_HAIR";
export const UPDATE_EYES = "UPDATE_EYES";
//health point actions
export const UPDATE_MAX_HP = "UPDATE_MAX_HP";
export const UPDATE_CURRENT_HP = "UPDATE_CURRENT_HP";
export const UPDATE_NONLETHAL = "UPDATE_NONLETHAL";
export const UPDATE_INITIATIVE_MOD = "UPDATE_INITIATIVE_MOD";
export const UPDATE_DR = "UPDATE_DR";
//stat point actions
export const INCREMENT_STR = "INCREMENT_STR";
export const INCREMENT_DEX = "INCREMENT_DEX";
export const INCREMENT_CON = "INCREMENT_CON";
export const INCREMENT_INT = "INCREMENT_INT";
export const INCREMENT_WIS = "INCREMENT_WIS";
export const INCREMENT_CHA = "INCREMENT_CHA";
export const DECREMENT_STR = "DECREMENT_STR";
export const DECREMENT_DEX = "DECREMENT_DEX";
export const DECREMENT_CON = "DECREMENT_CON";
export const DECREMENT_INT = "DECREMENT_INT";
export const DECREMENT_WIS = "DECREMENT_WIS";
export const DECREMENT_CHA = "DECREMENT_CHA";
export const INCREMENT_STR_TEMP = "INCREMENT_STR_TEMP";
export const INCREMENT_DEX_TEMP = "INCREMENT_DEX_TEMP";
export const INCREMENT_CON_TEMP = "INCREMENT_CON_TEMP";
export const INCREMENT_INT_TEMP = "INCREMENT_INT_TEMP";
export const INCREMENT_WIS_TEMP = "INCREMENT_WIS_TEMP";
export const INCREMENT_CHA_TEMP = "INCREMENT_CHA_TEMP";
export const DECREMENT_STR_TEMP = "DECREMENT_STR_TEMP";
export const DECREMENT_DEX_TEMP = "DECREMENT_DEX_TEMP";
export const DECREMENT_CON_TEMP = "DECREMENT_CON_TEMP";
export const DECREMENT_INT_TEMP = "DECREMENT_INT_TEMP";
export const DECREMENT_WIS_TEMP = "DECREMENT_WIS_TEMP";
export const DECREMENT_CHA_TEMP = "DECREMENT_CHA_TEMP";

//skill actions
export const UPDATE_SKILL_RANK = "UPDATE_SKILL_RANK";

